
jobs:
- name: job-docker-terraform
  public: true
  serial: true
  plan:
  - aggregate:
    - get: docker-terraform
      resource: git-docker-terraform
      trigger: true
    - get: terraform-release
      resource: terraform-version
      trigger: true
  - task: get-terraform
    file: docker-terraform/ci/build.yml
  - put: docker-terraform-image
    params:
      build: get-terraform
      tag: terraform-release/version
      tag_prefix: v



resources:
# FIX if terraform uses github release
- name: terraform-version
  type: git
  source:
    uri: https://gist.github.com/longnguyen11288/88def20236954031a007.git

- name: git-docker-terraform
  type: git
  source:
    uri: https://github.com/starkandwayne/docker-terraform.git
    access_token: {{github-access-token}}

- name: docker-terraform-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/terraform
